name: Build and Deploy to Render

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t my-flask-app .

      # Step 3: Deploy to Render
      - name: Deploy to Render
        run: |
          curl -X POST "https://api.render.com/v1/services/<srv-css9r9i3esus739jssn0>/deploys" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"clearCache": true}'
  