name: Deploy Docker App to Render

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t myusername/housepricing:v1 .
          docker push myusername/housepricing:v1

      - name: Trigger Render Deployment
        run: |
          curl -X POST "https://api.render.com/v1/services/srv-cssdvq52ng1s73ak18tg/deploys" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
