name: Deploy Docker App to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t my-app .

    - name: Log in to DockerHub (if needed)
      run: |
        echo ${{ secrets.DOCKER_USERNAME }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker image to DockerHub (if needed)
      run: |
        docker push my-app

    - name: Trigger deployment on Render
      run: |
        curl -X POST "https://api.render.com/deploy/srv-cssdvq52ng1s73ak18tg?key=${{ secrets.RENDER_API_KEY }}"
